name: 'Fibaro'
packageKey: 'fibaro-hc2'
permissions:
  lan: {}
  discovery: {}
description: "SmartThings Edge driver for Fibaro HC2 and HC3 controllers via Local API"
vendorSupportInformation: "https://support.smartthings.com"
