name: 'Fibaro HC'
packageKey: 'fibaro-hc2'
permissions:
  lan: {}
  discovery: {}
description: "SmartThings Edge driver for Fibaro HC2 manual onboarding and Fibaro HC3 mDNS-discovered Local API devices"
vendorSupportInformation: "https://support.smartthings.com"
